# Generated by Django 3.2 on 2024-06-26 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('document', models.ImageField(blank=True, null=True, upload_to='expenses/')),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('depleted_date', models.DateField(blank=True, null=True)),
                ('depleted_date_time', models.DateTimeField(blank=True, null=True)),
                ('depleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FundReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('document', models.ImageField(blank=True, null=True, upload_to='funds/')),
            ],
        ),
        migrations.CreateModel(
            name='NetWorth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FundExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.expense')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.fund'),
        ),
        migrations.AddField(
            model_name='expense',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
