# Generated by Django 3.2 on 2024-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundexpenditure',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundreceived',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
