# Generated by Django 3.2 on 2024-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalexpense',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalfundexpenditure',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalnetworth',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalreceivedfund',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
