# Generated by Django 3.2 on 2024-06-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finances', '0003_auto_20240628_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfundexpenditure',
            name='net_worth_amount',
            field=models.FloatField(default=0),
        ),
    ]
