# Generated by Django 3.2 on 2024-07-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finances', '0005_auto_20240704_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalexpense',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterModelOptions(
            name='personalfundexpenditure',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='personalfundadded',
            name='net_worth_amount',
            field=models.FloatField(default=0),
        ),
    ]
