# Generated by Django 3.2 on 2024-07-05 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_finances', '0006_auto_20240705_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNetWorthFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('amount_added', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('removed', models.BooleanField(default=False)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_finances.personalexpense')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_finances.personalfund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
