# Generated by Django 3.2 on 2024-07-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finances', '0007_personalnetworthflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfundadded',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
