# Generated by Django 3.2 on 2024-07-08 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_finances', '0008_personalfundadded_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTransferMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalFundTransferred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('removed', models.BooleanField(default=False)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_finances.personaltransfermode')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_receiver', to='personal_finances.personalfund')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_sender', to='personal_finances.personalfund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
